"""M1 Layer-3 reopen-equivalence harness (drives SOLIDWORKS via combridge).

Validates the M1 gate: a SWFormat-written file reopens in real SW with
equivalent semantics. See
``research/empirical_findings/m1_writer_roundtrip/log.md``.

    python test/harness/layer3_reopen.py --session pid:NNNN --file PATH \
        [--doc part|assembly|drawing] [--mode redeflate|lazy] [--combridge EXE]

What it does:
  1. Parse ``--file``; in ``redeflate`` mode re-compress every stream to
     its own decompressed content (logical content identical, byte layout
     shifted — the real test of TOC-offset tolerance). Write the echo into
     ``research/empirical_findings/m1_writer_roundtrip/samples/`` (gitignored).
  2. Extract semantics from the ORIGINAL and the ECHO via a generated .csx
     (configs, custom props, mass, bodies/sheets).
  3. Compare. Report per-field equivalence + whether the echo opened clean.

Exit 0 = echo opened AND semantically equivalent; 1 = mismatch / open
failure; 2 = usage/IO error.

NOTE: never uses the combridge MRU default — always an explicit
``--session pid:NNNN`` (the user runs parallel SW sessions).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "src"))

from swformat.io.reader import read_document  # noqa: E402
from swformat.io.writer import force_redeflate_all, serialize, set_stream_payload  # noqa: E402

EXP = ROOT / "research" / "empirical_findings" / "m1_writer_roundtrip"
SAMPLES = EXP / "samples"
SCRATCH = EXP / "scratch"
DEFAULT_COMBRIDGE = Path("combridge.exe")  # on PATH, or pass --combridge
DOCTYPE = {"part": 1, "assembly": 2, "drawing": 3}

# Generated extract script. Placeholder __SRC__ / __DOCTYPE__ substituted.
# GetAll3 uses ref (PIA quirk); mass for part/assembly; sheets for drawing.
_EXTRACT_CSX = r"""// generated by layer3_reopen.py — extract semantics, print key=value lines
string src = @"__SRC__";
const int swDocType = __DOCTYPE__;
const int silent = 1;
int e = 0, w = 0;
IModelDoc2 doc = swApp.OpenDoc6(src, swDocType, silent, "", ref e, ref w);
if (doc is null) { Console.WriteLine($"OPENFAIL e={e} w={w}"); return 2; }
Console.WriteLine($"OPEN e={e} w={w}");
object cfgObj = doc.GetConfigurationNames();
string[] cfgs = cfgObj as string[];
if (cfgs != null) { Array.Sort(cfgs); foreach (var c in cfgs) Console.WriteLine($"CONFIG={c}"); }
CustomPropertyManager cpm = doc.Extension.CustomPropertyManager[""]; // PIA: indexed property, not a method
object pn = null, pt = null, pv = null, pr = null, pl = null;
cpm.GetAll3(ref pn, ref pt, ref pv, ref pr, ref pl);
string[] names = pn as string[]; string[] vals = pv as string[]; bool[] links = pl as bool[];
// Emit value + link flag. Filename-linked props (e.g. PARTNO linked to
// SW-File Name) evaluate to the echo's different filename — an expected,
// correct difference, not a writer bug — so the comparator skips linked props.
if (names != null) {
    for (int i = 0; i < names.Length; i++) {
        string v = (vals != null && i < vals.Length) ? vals[i] : "";
        int linked = (links != null && i < links.Length && links[i]) ? 1 : 0;
        Console.WriteLine($"PROP|{names[i]}|{v}|{linked}");
    }
}
try {
    if (swDocType == 1) {
        object[] bodies = (object[])((PartDoc)doc).GetBodies2(0, true);
        Console.WriteLine($"BODIES={(bodies?.Length ?? 0)}");
    } else if (swDocType == 3) {
        object sObj = ((DrawingDoc)doc).GetSheetNames();
        string[] sheets = sObj as string[];
        if (sheets != null) { Array.Sort(sheets); foreach (var s in sheets) Console.WriteLine($"SHEET={s}"); }
    }
} catch (Exception ex) { Console.WriteLine($"TYPEINFO_ERR={ex.Message}"); }
try {
    if (swDocType != 3) {
        MassProperty mp = (MassProperty)doc.Extension.CreateMassProperty();
        Console.WriteLine($"MASS={mp.Mass:F6}");
    }
} catch (Exception ex) { Console.WriteLine($"MASS_ERR={ex.Message}"); }
swApp.CloseDoc(doc.GetTitle());
Console.WriteLine("DONE");
return 0;
"""


def _extract(combridge: Path, session: str, src: Path, doctype: int, label: str) -> dict | None:
    SCRATCH.mkdir(parents=True, exist_ok=True)
    csx = SCRATCH / f"extract_{label}.csx"
    csx.write_text(_EXTRACT_CSX.replace("__SRC__", str(src)).replace("__DOCTYPE__", str(doctype)),
                   encoding="utf-8")
    cmd = [str(combridge), "solidworks", "--session", session, "run-script", str(csx), "-"]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    out = proc.stdout or ""
    print(f"  [{label}] combridge rc={proc.returncode}")
    for ln in out.splitlines():
        print(f"    | {ln}")
    if proc.returncode != 0 or "OPENFAIL" in out:
        for ln in (proc.stderr or "").splitlines():
            print(f"    !! {ln}")
        return None
    facts: dict = {"configs": [], "props": {}, "linked_props": set(), "sheets": [],
                   "bodies": None, "mass": None, "opened": False, "open_warnings": None,
                   "stem": src.stem}
    for ln in out.splitlines():
        if ln.startswith("OPEN "):
            facts["opened"] = True
            facts["open_warnings"] = ln
        elif ln.startswith("CONFIG="):
            facts["configs"].append(ln[len("CONFIG="):])
        elif ln.startswith("PROP|"):
            parts = ln.split("|")
            name, val = parts[1], parts[2]
            linked = len(parts) > 3 and parts[3] == "1"
            facts["props"][name] = val
            if linked:
                facts["linked_props"].add(name)
        elif ln.startswith("SHEET="):
            facts["sheets"].append(ln[len("SHEET="):])
        elif ln.startswith("BODIES="):
            facts["bodies"] = int(ln[len("BODIES="):])
        elif ln.startswith("MASS="):
            facts["mass"] = round(float(ln[len("MASS="):]), 5)
    return facts


def _compare(orig: dict, echo: dict) -> list[str]:
    """Return a list of mismatch descriptions ([] == equivalent)."""
    issues = []
    if not echo.get("opened"):
        return ["echo did NOT open"]
    if sorted(orig["configs"]) != sorted(echo["configs"]):
        issues.append(f"configs differ: {orig['configs']} vs {echo['configs']}")
    # Skip filename-derived props: those flagged LinkToProperty, AND those
    # whose value equals their own file's stem (e.g. PARTNO = $PRP:"SW-File
    # Name", which SW evaluates to the filename without setting the link flag).
    linked = orig.get("linked_props", set()) | echo.get("linked_props", set())
    o_stem, e_stem = orig.get("stem"), echo.get("stem")
    keys = (set(orig["props"]) | set(echo["props"])) - linked
    for k in sorted(keys):
        ov, ev = orig["props"].get(k), echo["props"].get(k)
        if ov == ev:
            continue
        if ov == o_stem or ev == e_stem:  # filename-derived — expected to differ
            continue
        issues.append(f"prop[{k}]: {ov!r} vs {ev!r}")
    if sorted(orig["sheets"]) != sorted(echo["sheets"]):
        issues.append(f"sheets differ: {orig['sheets']} vs {echo['sheets']}")
    if orig["bodies"] != echo["bodies"]:
        issues.append(f"body count: {orig['bodies']} vs {echo['bodies']}")
    if orig["mass"] != echo["mass"]:
        issues.append(f"mass: {orig['mass']} vs {echo['mass']}")
    return issues


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="M1 Layer-3 reopen-equivalence harness")
    p.add_argument("--session", required=True)
    p.add_argument("--file", type=Path, required=True)
    p.add_argument("--doc", choices=list(DOCTYPE), default="part")
    p.add_argument("--mode", choices=["redeflate", "lazy"], default="redeflate")
    p.add_argument("--only-stream", help="redeflate ONLY this stream (characterize "
                   "which streams break reopen); implies --mode redeflate")
    p.add_argument("--echo-beside", action="store_true",
                   help="write the echo beside the source (needed for assemblies/"
                        "drawings so component references resolve)")
    p.add_argument("--combridge", type=Path, default=DEFAULT_COMBRIDGE)
    args = p.parse_args(argv)

    if not args.file.exists():
        print(f"ERROR: not found: {args.file}", file=sys.stderr)
        return 2
    SAMPLES.mkdir(parents=True, exist_ok=True)
    doctype = DOCTYPE[args.doc]

    # Build the echo.
    doc = read_document(args.file)
    if doc.fmt != "modern":
        print(f"ERROR: {args.file} is {doc.fmt}, not modern", file=sys.stderr)
        return 2
    if args.only_stream:
        payload = doc.streams().get(args.only_stream)
        if payload is None:
            print(f"ERROR: stream not found: {args.only_stream}", file=sys.stderr)
            return 2
        n = set_stream_payload(doc, args.only_stream, payload)
        print(f"re-deflated ONLY '{args.only_stream}' ({n} chunk(s))")
        args.mode = "redeflate"
    elif args.mode == "redeflate":
        n = force_redeflate_all(doc)
        print(f"re-deflated {n} streams")
    echo_dir = args.file.parent if args.echo_beside else SAMPLES
    echo = echo_dir / f"{args.file.stem}__echo_{args.mode}{args.file.suffix}"
    echo.write_bytes(serialize(doc))
    print(f"echo: {echo}  ({echo.stat().st_size:,} B; original {args.file.stat().st_size:,} B)\n")

    print("=== extract: ORIGINAL ===")
    f_orig = _extract(args.combridge, args.session, args.file, doctype, "orig")
    print("=== extract: ECHO ===")
    f_echo = _extract(args.combridge, args.session, echo, doctype, "echo")

    print("\n=== EQUIVALENCE ===")
    if f_orig is None:
        print("  original failed to open/extract — cannot compare")
        return 2
    if f_echo is None:
        print("  ECHO FAILED TO OPEN — re-deflated file rejected by SW (TOC/offset risk REAL)")
        return 1
    issues = _compare(f_orig, f_echo)
    if not issues:
        print(f"  EQUIVALENT — echo opens; configs={f_orig['configs']} "
              f"props={len(f_orig['props'])} mass={f_orig['mass']} "
              f"bodies={f_orig['bodies']} sheets={len(f_orig['sheets'])}")
        return 0
    print("  NOT EQUIVALENT:")
    for i in issues:
        print(f"    - {i}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
