"""Layer-3 tests — CArchive read primitives (M5.1, read side).

Covers the CString primitive and the CusProps user-property reader. The
key invariant: the property NAMES read from the binary ``Contents/CusProps``
store equal the user-defined names in ``docProps/custom.xml`` (they are the
same registered set — the M1.5/M2 intersection). Marked ``layer2`` (pure
Python, no SW).
"""
from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "src"))

import swformat  # noqa: E402
from swformat.api.properties import read_properties  # noqa: E402
from swformat.carchive.archive import (  # noqa: E402
    ClassDef,
    TagKind,
    read_class_def,
    read_count,
    read_object_tag,
    scan_class_defs,
    write_class_def,
    write_count,
    write_object_tag,
)
from swformat.carchive.archive import TagKind as _TK  # noqa: E402
from swformat.carchive.cstring import encode_cstring, read_cstring  # noqa: E402
from swformat.carchive.cusprops import (  # noqa: E402
    CustomPropsError,
    add_text_properties,
    check_user_list_coverage,
    parse_container_header,
    read_cusprops,
    read_cutlist_props,
    reserialize_header,
    roundtrip,
    serialize_user_records,
    set_cutlist_value,
    walk_cutlist_records,
    walk_user_records,
)

# Synthetic cut-list fixture (generated by gen_weldment_min.csx — a new empty
# weldment + a user-text cut-list property "SWFTEST"=hello). No client data, so
# it is committable and its values can be asserted. SW-verified that editing
# SWFTEST's value here reopens changed in SOLIDWORKS (errors=0, warnings=0).
_WELDMENT_MIN = ROOT / "research" / "empirical_findings" / "cusprops_carchive" / "weldment_min.SLDPRT"
_skip_weldment = pytest.mark.skipif(
    not _WELDMENT_MIN.exists(), reason="synthetic weldment_min fixture absent"
)


def _weldment_cusprops() -> bytes:
    return swformat.read_document(_WELDMENT_MIN).streams()["Contents/CusProps"]


def test_cstring_roundtrip() -> None:
    for s in ["", "REVISION", "docProps/custom.xml", "a & b", "ZZ_TEST", "héllo"]:
        enc = encode_cstring(s)
        got = read_cstring(enc, 0)
        assert got is not None
        text, nxt = got
        assert text == s and nxt == len(enc)
    # non-CString bytes return None
    assert read_cstring(b"\x00\x01\x02\x03", 0) is None


def test_cstring_roundtrip_astral() -> None:
    """Astral chars (surrogate pairs) round-trip: length is UTF-16 code units.

    Regression: encode_cstring used len(text) (code points), which writes too
    few bytes for the declared length when a code point is two UTF-16 code
    units, breaking the round-trip. Length must be len(enc)//2.
    """
    for s in ["\U00020bb7", "\U0001F600 part", "mix \U0001F4801 end"]:
        enc = encode_cstring(s)
        # declared length == UTF-16 code units, not Python str length
        assert enc[3] == len(s.encode("utf-16-le")) // 2
        got = read_cstring(enc, 0)
        assert got is not None
        text, nxt = got
        assert text == s and nxt == len(enc)


def test_object_tag_classify_and_roundtrip() -> None:
    assert read_object_tag(b"\x00\x00", 0) == (TagKind.NULL, 0, 2)
    assert read_object_tag(b"\xff\xff", 0) == (TagKind.NEW_CLASS, 0, 2)
    assert read_object_tag(b"\x0b\x80", 0) == (TagKind.CLASS_REF, 0x0b, 2)
    assert read_object_tag(b"\x05\x00", 0) == (TagKind.OBJECT_REF, 5, 2)
    assert write_object_tag(TagKind.NULL) == b"\x00\x00"
    assert write_object_tag(TagKind.NEW_CLASS) == b"\xff\xff"
    assert write_object_tag(TagKind.CLASS_REF, 0x0b) == b"\x0b\x80"
    assert write_object_tag(TagKind.OBJECT_REF, 5) == b"\x05\x00"


def test_class_def_roundtrip() -> None:
    blob = write_class_def(1, "moCusPropMgr_c")
    assert blob == b"\x01\x00\x0e\x00moCusPropMgr_c"
    schema, name, nxt = read_class_def(blob, 0)
    assert (schema, name, nxt) == (1, "moCusPropMgr_c", len(blob))


def test_scan_class_defs_finds_defs_in_order() -> None:
    """Forward-scan recovers each NEW_CLASS def (offset, schema, name) in file
    order, and is not fooled by a bare ``FF FF`` (NEW_CLASS tag) that is not
    followed by a valid class framing."""
    a = write_class_def(1, "moDrawing_c")
    b = write_class_def(1, "moLengthParameter_c")
    c = write_class_def(1, "moDisplayDistanceDim_c")
    # FF FF tags introduce each def; junk + a lone FF FF (no valid framing) between.
    blob = (b"\xff\xff" + a + b"\x00\x00body" +
            b"\xff\xff" + b +
            b"\xff\xff\x99\x99\x99\x99" +            # FF FF with implausible schema/name
            b"\xff\xff" + c + b"tail")
    defs = scan_class_defs(blob)
    assert [d.name for d in defs] == ["moDrawing_c", "moLengthParameter_c",
                                      "moDisplayDistanceDim_c"]
    assert all(isinstance(d, ClassDef) and d.schema == 1 for d in defs)
    # offsets strictly increasing (definition order) and point at the FF FF tag
    offs = [d.offset for d in defs]
    assert offs == sorted(offs)
    assert blob[offs[0]:offs[0] + 2] == b"\xff\xff"


def test_scan_class_defs_suffix_filter_and_empty() -> None:
    """The default accepts any identifier (so non-``_c`` classes like
    ``moDrSheet`` / ``sgSketch`` are found); an optional ``name_suffix`` filters;
    a stream with no class defs yields an empty list."""
    assert scan_class_defs(b"no class defs here, just text \xff\xff\x01\x00") == []
    # a non-_c identifier (like the real moDrSheet/sgSketch) IS found by default...
    blob = b"\xff\xff" + write_class_def(1, "moDrSheet")
    assert [d.name for d in scan_class_defs(blob)] == ["moDrSheet"]
    # ...but can be excluded with an explicit suffix filter.
    assert scan_class_defs(blob, name_suffix=b"_c") == []
    assert [d.name for d in scan_class_defs(
        b"\xff\xff" + write_class_def(1, "moThing_c"), name_suffix=b"_c"
    )] == ["moThing_c"]


def test_read_count_escape() -> None:
    for v, expect_len in [(0, 2), (10, 2), (0xFFFE, 2), (0xFFFF, 6), (0x10000, 6),
                          (0xFFFFFFFF, 14), (0x1_0000_0000, 14)]:
        blob = write_count(v)
        assert len(blob) == expect_len
        assert read_count(blob, 0) == (v, expect_len)


def test_carchive_primitives_on_real_header() -> None:
    """The real CusProps stream begins NEW_CLASS + the moCusPropMgr_c def."""
    target = Path(r"C:\path\to\your\example.SLDPRT")  # set to a local part to enable
    if not target.exists():
        pytest.skip("real part fixture not present (set the path to a local file)")
    data = swformat.read_document(target).streams().get("Contents/CusProps")
    if data is None:
        pytest.skip("no CusProps")
    kind, _, off = read_object_tag(data, 0)
    assert kind is TagKind.NEW_CLASS
    schema, name, _ = read_class_def(data, off)
    assert schema == 1 and name == "moCusPropMgr_c"


def test_weldment_dimele_user_records_roundtrip() -> None:
    """A v19000 weldment (multi-element records incl. moCusPropDimEle_c) parses
    and its user-record region re-serializes byte-exact.

    Guards the flag-as-COUNT + moCusPropDimEle_c (`cstr2_dim` + 22-byte trailer)
    decode. Scans a gitignored local samples tree for a part whose CusProps uses
    moCusPropDimEle_c; skips if none present (real CAD files are local-only and
    never committed). No third-party data is asserted, only structural round-trip.
    """
    from swformat.carchive import cusprops as cp

    samples = ROOT / "research" / "empirical_findings" / "twin_save_baseline" / "samples"
    target = None
    if samples.exists():
        for p in sorted(samples.rglob("*.SLDPRT")):
            if p.name.lower().startswith(("twina", "twinb")):
                continue
            try:
                cus = swformat.read_document(p).streams().get("Contents/CusProps")
            except Exception:
                continue
            if cus and b"moCusPropDimEle_c" in cus:
                target = (p, cus)
                break
    if target is None:
        pytest.skip("no staged weldment with moCusPropDimEle_c present")
    _p, cus = target
    n_props, first_off, _ = cp.parse_container_header(cus)
    recs, end_off = cp.walk_user_records(cus)
    assert len(recs) == n_props
    # the structural re-emit of the user-record region is byte-exact
    assert cp.serialize_user_records(cus) == cus[first_off:end_off]


def test_add_text_properties_byte_exact_vs_sw() -> None:
    """The CusProps writer reproduces SOLIDWORKS's own add-2-properties output.

    Ground truth: c_B0 (10 props) and c_B2 (c_B0 + ZZ_ONE/ZZ_TWO added by SW),
    both SW-saved to one fixed filename (no embedded-name artifact). Adding the
    same two text properties via our writer must yield c_B2 byte-for-byte.
    """
    base = ROOT / "research" / "empirical_findings" / "cusprops_carchive"
    b0p, b2p = base / "c_B0.SLDPRT", base / "c_B2.SLDPRT"
    if not (b0p.exists() and b2p.exists()):
        pytest.skip("CusProps diff-pair (c_B0/c_B2) not present")
    b0 = swformat.read_document(b0p).streams()["Contents/CusProps"]
    b2 = swformat.read_document(b2p).streams()["Contents/CusProps"]
    got = add_text_properties(b0, [("ZZ_ONE", "valuethefirst"), ("ZZ_TWO", "second_val")])
    assert got == b2, "writer output is not byte-identical to SOLIDWORKS's"


def test_parse_container_header_raises_custompropserror() -> None:
    """Malformed CArchive raises CustomPropsError, not a bare NameError.

    Regression: ``cusprops.py`` referenced ``CustomPropsError`` without
    importing it, so every error path raised ``NameError`` instead. Feed a
    NEW_CLASS whose name isn't the expected root class to hit that path.
    """
    bogus = b"\xff\xff\x01\x00\x04\x00XXXX"  # NEW_CLASS schema=1 namelen=4 "XXXX"
    with pytest.raises(CustomPropsError):
        parse_container_header(bogus)


def _corpus_with_cusprops() -> list[tuple[str, Path]]:
    cfg = ROOT / "test" / "corpus" / "corpus.config.json"
    if not cfg.exists():
        return []
    out = []
    for e in json.loads(cfg.read_text(encoding="utf-8")).get("files", []):
        p = Path(e["path"])
        if p.exists() and "Contents/CusProps" in swformat.read_document(p).streams():
            out.append((e["tag"], p))
    return out


CORPUS = _corpus_with_cusprops()
_IDS = [t for t, _ in CORPUS]


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_container_header_parse(tag: str, path: Path) -> None:
    """The structural header parser agrees with the heuristic reader + lands clean."""
    from swformat.carchive.archive import read_object_tag

    cusprops = swformat.read_document(path).streams()["Contents/CusProps"]
    n_props, first_off, class_map = parse_container_header(cusprops)
    # property count matches the heuristic name reader
    assert n_props == len(read_cusprops(cusprops))
    assert class_map[1] == "moCusPropMgr_c"
    if n_props == 0:
        return  # empty store: only the root class, no container chain/records
    # non-empty: the five outer container classes, in order
    assert [class_map[i] for i in range(1, 6)] == [
        "moCusPropMgr_c", "moCusPropContainer_c", "moFilePropContainer_c",
        "suObList", "moAdvCusPropList_c",
    ]
    # first record offset lands on a NEW_CLASS tag (the first moAdvCusProp_c)
    kind, _, _ = read_object_tag(cusprops, first_off)
    assert kind is _TK.NEW_CLASS


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_cusprops_names_match_xml(tag: str, path: Path) -> None:
    """Binary CusProps property names == docProps/custom.xml user-prop names."""
    cusprops = swformat.read_document(path).streams()["Contents/CusProps"]
    bin_names = set(read_cusprops(cusprops))
    xml_names = set(read_properties(path))
    assert bin_names == xml_names, (
        f"{tag}: CusProps vs XML name mismatch; "
        f"only-bin={sorted(bin_names - xml_names)} only-xml={sorted(xml_names - bin_names)}"
    )


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_walk_user_records(tag: str, path: Path) -> None:
    """The record walker segments the property list exactly and matches the reader."""
    data = swformat.read_document(path).streams()["Contents/CusProps"]
    records, end_off = walk_user_records(data)
    n_props, first_off, _ = parse_container_header(data)

    # one record per property, in the same name->value mapping as the reader
    assert len(records) == n_props
    assert {r["name"]: r["value"] for r in records} == read_cusprops(data)
    if n_props == 0:
        return

    # records are contiguous and span exactly [first_off, end_off)
    assert records[0]["start"] == first_off
    for a, b in itertools.pairwise(records):
        assert a["end"] == b["start"]
    assert records[-1]["end"] == end_off

    # the walk lands on the suObList terminator 00 00 (CObList end of the list)
    assert data[end_off:end_off + 2] == b"\x00\x00"
    # for a doc with a cut list, the cutlist container NEW_CLASS follows it
    cut = data.find(b"moCutListPropContainer_c")
    if cut >= 0:
        kind, _, _ = read_object_tag(data, end_off + 2)
        assert kind is _TK.NEW_CLASS


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_user_list_coverage_no_orphan_bytes(tag: str, path: Path) -> None:
    """M5.1 Step-1 gate: the structured walk covers the user list with no orphans.

    ``check_user_list_coverage`` raises ``CustomPropsError`` if the record
    walk drifts (a wrong value-element body shape would land ``end_off`` off
    the ``suObList`` terminator / cut-list container). Passing across the
    whole corpus — part-with-cutlist, assembly-without, empty store — proves
    the decode generalizes beyond the single diff-pair it was derived from.
    """
    data = swformat.read_document(path).streams()["Contents/CusProps"]
    report = check_user_list_coverage(data)  # raises on any violation
    assert report["records"] == report["n_props"]
    assert report["end_off"] <= report["total_len"]
    # the record region abuts the header (no gap, no overlap)
    if report["n_props"]:
        assert report["end_off"] >= report["first_record_off"]


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_reserialize_header_byte_exact(tag: str, path: Path) -> None:
    """The header is rebuilt STRUCTURALLY (not sliced) and must match the bytes.

    A wrong model of the container-class chain, the moCusPropMgr_c scalar
    body, or a count's width/position would make the structural re-emission
    differ from the original header slice — so this is a real falsification
    gate for the M5.1 header model, validated across the corpus.
    """
    data = swformat.read_document(path).streams()["Contents/CusProps"]
    _n, first_off, _ = parse_container_header(data)
    assert reserialize_header(data) == data[:first_off]


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_serialize_user_records_byte_exact(tag: str, path: Path) -> None:
    """User records are re-emitted STRUCTURALLY and must match the bytes.

    Re-encodes every object tag, class def and CString from the decoded model
    (not slicing), so this falsifies a wrong record model across all variants
    present in the corpus: novalue (flag 0), StringElem, PRP, MassProp — and
    both first-occurrence NEW_CLASS and subsequent CLASS_REF tags. Also proves
    the CString codec is bijective on real corpus strings.
    """
    data = swformat.read_document(path).streams()["Contents/CusProps"]
    _n, first_off, _ = parse_container_header(data)
    _records, end_off = walk_user_records(data)
    assert serialize_user_records(data) == data[first_off:end_off]


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_cusprops_roundtrip(tag: str, path: Path) -> None:
    """M5.1 Step-1 acceptance gate: reassemble from the model == original.

    Header is re-emitted structurally; user records and the cut-list/dump
    tail are carried verbatim (tail-bytes invariant). ``roundtrip`` raises on
    any drift, so simply calling it across the corpus is the gate.
    """
    data = swformat.read_document(path).streams()["Contents/CusProps"]
    assert roundtrip(data) == data


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus file with Contents/CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_read_cutlist_props_shape(tag: str, path: Path) -> None:
    """Cut-list reader returns a clean {str: str} dict (no crash on any file)."""
    cusprops = swformat.read_document(path).streams()["Contents/CusProps"]
    cut = read_cutlist_props(cusprops)
    assert isinstance(cut, dict)
    assert all(isinstance(k, str) and isinstance(v, str) for k, v in cut.items())


def test_read_cutlist_props_known_part() -> None:
    """A part with a cut list exposes its resolved cut-list values."""
    target = Path(r"C:\path\to\your\example.SLDPRT")  # set to a local part to enable
    if not target.exists():
        pytest.skip("real part fixture not present (set the path to a local file)")
    cusprops = swformat.read_document(target).streams().get("Contents/CusProps")
    if cusprops is None:
        pytest.skip("no CusProps")
    cut = read_cutlist_props(cusprops)
    # resolved values, not the $PRP formula
    assert cut.get("MATERIAL") == "Plain Carbon Steel"
    assert cut.get("QUANTITY") == "1"


# --------------------------------------------------------------------------- #
# Cut-list structural walker + value editor (M5.1) — synthetic fixture.
# --------------------------------------------------------------------------- #

@pytest.mark.layer2
@_skip_weldment
def test_walk_cutlist_records_synthetic() -> None:
    """The structural walker finds the synthetic weldment's 3 cut-list props,
    correctly classifying user-text vs formula-linked."""
    recs = walk_cutlist_records(_weldment_cusprops())
    by = {r["name"]: r for r in recs}
    assert {"MATERIAL", "QUANTITY", "SWFTEST"} <= set(by)
    # MATERIAL/QUANTITY are system-defined (formula-linked) -> not editable
    assert by["MATERIAL"]["linked"] and by["QUANTITY"]["linked"]
    # SWFTEST is the user-text property we added -> editable, has an elem-value
    assert not by["SWFTEST"]["linked"]
    assert by["SWFTEST"]["elem_value_span"] is not None
    assert by["SWFTEST"]["value"] == "hello"


@pytest.mark.layer2
@_skip_weldment
def test_set_cutlist_value_noop_is_identity() -> None:
    """Re-writing a cut-list value to its current value is a byte no-op
    (proves the located spans are exact)."""
    cus = _weldment_cusprops()
    assert set_cutlist_value(cus, "SWFTEST", "hello") == cus


@pytest.mark.layer2
@_skip_weldment
def test_set_cutlist_value_edits_only_target() -> None:
    """Editing a user-text cut-list value changes only that property; the
    others and the property count are preserved."""
    cus = _weldment_cusprops()
    out = set_cutlist_value(cus, "SWFTEST", "CHANGED_VALUE")
    after = {r["name"]: r["resolved"] for r in walk_cutlist_records(out)}
    assert after["SWFTEST"] == "CHANGED_VALUE"
    assert after["MATERIAL"] == "Plain Carbon Steel"
    assert after["QUANTITY"] == "1"
    # all 3 authoritative copies updated -> re-walk value is consistent too
    sw = next(r for r in walk_cutlist_records(out) if r["name"] == "SWFTEST")
    assert sw["value"] == "CHANGED_VALUE" and sw["resolved"] == "CHANGED_VALUE"


@pytest.mark.layer2
@_skip_weldment
def test_set_cutlist_value_rejects_linked_and_unknown() -> None:
    """Formula-linked (system-defined) and unknown props are rejected."""
    cus = _weldment_cusprops()
    with pytest.raises(CustomPropsError):
        set_cutlist_value(cus, "MATERIAL", "x")   # formula-linked
    with pytest.raises(CustomPropsError):
        set_cutlist_value(cus, "NO_SUCH_PROP", "x")


@pytest.mark.layer2
@_skip_weldment
def test_edit_cutlist_value_api_roundtrip(tmp_path: Path) -> None:
    """API edit_cutlist_value writes a file the reader reads back changed;
    formula-linked props are rejected."""
    from swformat.api.properties import edit_cutlist_value, read_cutlist_properties
    from swformat.carchive.cusprops import CustomPropsError

    out = tmp_path / "cutlist_edited.SLDPRT"
    edit_cutlist_value(_WELDMENT_MIN, "SWFTEST", "API_ROUNDTRIP", out)
    after = read_cutlist_properties(out)
    assert after["SWFTEST"] == "API_ROUNDTRIP"
    assert after["MATERIAL"] == "Plain Carbon Steel"  # untouched
    with pytest.raises(CustomPropsError):
        edit_cutlist_value(_WELDMENT_MIN, "MATERIAL", "x", tmp_path / "x.SLDPRT")


@pytest.mark.layer2
@_skip_weldment
def test_read_cutlist_props_structural_clean() -> None:
    """The (now structural) reader returns exactly the synthetic weldment's
    cut-list props with correct resolved values — no value-as-name junk."""
    cut = read_cutlist_props(_weldment_cusprops())
    assert cut == {"MATERIAL": "Plain Carbon Steel", "QUANTITY": "1", "SWFTEST": "hello"}


# --------------------------------------------------------------------------- #
# Object-map ledger (M5.1 Step 2 — codec core). Self-contained: a hand-built
# CArchive stream with a length-prefixed body convention proves the index rule
# + byte-exact round-trip independent of any real per-class body parser.
# --------------------------------------------------------------------------- #

def _lp_body_len(data, offset, ctx):
    """Test oracle: each body is <u16 len><len bytes>."""
    import struct as _s
    ln = _s.unpack_from("<H", data, offset)[0]
    return offset + 2 + ln


def _lp_body(payload: bytes) -> bytes:
    import struct as _s
    return _s.pack("<H", len(payload)) + payload


def test_objmap_ledger_roundtrip_and_indices() -> None:
    from swformat.carchive.archive import (
        TagKind,
        write_class_def,
        write_object_tag,
    )
    from swformat.carchive.objmap import serialize_objmap, walk_objmap
    # Build: NEW_CLASS "Foo"(schema 1)+body, class-ref Foo + body, OBJECT_REF 2, NULL
    stream = (
        write_object_tag(TagKind.NEW_CLASS) + write_class_def(1, "Foo") + _lp_body(b"\xaa\xbb\xcc")
        + write_object_tag(TagKind.CLASS_REF, 1) + _lp_body(b"\xdd")
        + write_object_tag(TagKind.OBJECT_REF, 2)
        + write_object_tag(TagKind.NULL)
    )
    led = walk_objmap(stream, _lp_body_len)
    kinds = [e.kind for e in led.entries]
    assert kinds == [TagKind.NEW_CLASS, TagKind.CLASS_REF, TagKind.OBJECT_REF, TagKind.NULL]
    # MFC index rule: Foo class=1, first Foo obj=2, second Foo obj=3
    assert led.entries[0].class_index == 1 and led.entries[0].obj_index == 2
    assert led.entries[0].class_name == "Foo"
    assert led.entries[1].class_index == 1 and led.entries[1].obj_index == 3
    assert led.entries[2].ref_index == 2
    assert led.end_offset == len(stream)
    # byte-exact round-trip (the Step-A gate)
    assert serialize_objmap(led) == stream


def test_objmap_ledger_multiclass_indices() -> None:
    """Two NEW_CLASS defs advance the shared index by 2 each."""
    from swformat.carchive.archive import TagKind, write_class_def, write_object_tag
    from swformat.carchive.objmap import walk_objmap
    stream = (
        write_object_tag(TagKind.NEW_CLASS) + write_class_def(1, "A") + _lp_body(b"\x01")
        + write_object_tag(TagKind.NEW_CLASS) + write_class_def(1, "B") + _lp_body(b"\x02")
        + write_object_tag(TagKind.CLASS_REF, 3) + _lp_body(b"\x03")  # new B object
    )
    led = walk_objmap(stream, _lp_body_len)
    assert led.entries[0].class_index == 1 and led.entries[0].obj_index == 2  # A
    assert led.entries[1].class_index == 3 and led.entries[1].obj_index == 4  # B
    assert led.entries[2].class_index == 3 and led.entries[2].obj_index == 5  # 2nd B
    assert led.class_names == {1: "A", 3: "B"}


def test_objmap_ledger_nested_index_accounting() -> None:
    """A body that serialized inline sub-objects advances the shared index by
    those nested objects too, so later top-level objects get correct indices."""
    import struct as _s

    from swformat.carchive.archive import TagKind, write_class_def, write_object_tag
    from swformat.carchive.objmap import serialize_objmap, walk_objmap

    # body convention for this test: <u16 len><u16 nested><len bytes>
    def body_len(data, offset, ctx):
        ln = _s.unpack_from("<H", data, offset)[0]
        nested = _s.unpack_from("<H", data, offset + 2)[0]
        return offset + 4 + ln, nested

    def body(payload: bytes, nested: int) -> bytes:
        return _s.pack("<HH", len(payload), nested) + payload

    stream = (
        # Outer: NEW_CLASS (class=1,obj=2); body declares 2 nested indices
        write_object_tag(TagKind.NEW_CLASS) + write_class_def(1, "Outer") + body(b"\xaa\xbb", 2)
        # Next: NEW_CLASS — must land on class=5,obj=6 (1 + 2 base + 2 nested = 5)
        + write_object_tag(TagKind.NEW_CLASS) + write_class_def(1, "Next") + body(b"\xcc", 0)
    )
    led = walk_objmap(stream, body_len)
    assert led.entries[0].class_index == 1 and led.entries[0].obj_index == 2
    assert led.entries[0].nested_indices == 2
    assert led.entries[1].class_index == 5 and led.entries[1].obj_index == 6
    assert serialize_objmap(led) == stream  # byte-exact despite nesting


# Header body sizes by class (from cusprops._object_map_walk): the CusProps
# container chain mgr -> container -> filecontainer -> suObList -> advlist.
_CUSPROPS_HEADER_BODY = {
    "moCusPropMgr_c": 16, "moCusPropContainer_c": 0, "moFilePropContainer_c": 0,
    "suObList": 2, "moAdvCusPropList_c": 2,
}


def _cusprops_header_oracle(data, offset, ctx):
    cn = ctx["class_name"]
    if cn not in _CUSPROPS_HEADER_BODY:
        raise AssertionError(f"unexpected header class {cn!r}")
    return offset + _CUSPROPS_HEADER_BODY[cn]


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_objmap_ledger_roundtrips_real_cusprops_header(tag: str, path: Path) -> None:
    """The object-map ledger walks the REAL CusProps header chain of a non-empty
    store and re-serializes it byte-exactly, assigning the known object-map
    indices (mgr=1, container=3, filecontainer=5, suObList=7, advlist=9)."""
    from swformat.carchive.cusprops import parse_container_header
    from swformat.carchive.objmap import serialize_objmap, walk_objmap

    cus = swformat.read_document(path).streams().get("Contents/CusProps")
    if cus is None:
        pytest.skip("no CusProps")
    try:
        n_props, first_off, _ = parse_container_header(cus)
    except CustomPropsError:
        pytest.skip("unparseable container header")
    if n_props == 0:
        pytest.skip("empty store (minimal-header special case)")
    led = walk_objmap(cus, _cusprops_header_oracle, stop=first_off)
    assert led.end_offset == first_off
    assert serialize_objmap(led) == cus[:first_off]
    assert led.class_names.get(1) == "moCusPropMgr_c"
    assert led.class_names.get(9) == "moAdvCusPropList_c"


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_objmap_ledger_roundtrips_user_records(tag: str, path: Path) -> None:
    """The ledger + cusprops_body_len oracle round-trip the full HEADER + all
    USER RECORDS of a real CusProps store byte-exactly (exercises nested
    inline-element index accounting on real data)."""
    from swformat.carchive.cusprops import (
        cusprops_body_len,
        parse_container_header,
        walk_user_records,
    )
    from swformat.carchive.objmap import serialize_objmap, walk_objmap

    cus = swformat.read_document(path).streams().get("Contents/CusProps")
    if cus is None:
        pytest.skip("no CusProps")
    try:
        n_props, _first, _ = parse_container_header(cus)
    except CustomPropsError:
        pytest.skip("unparseable container header")
    if n_props == 0:
        pytest.skip("empty store")
    _recs, end_off = walk_user_records(cus)
    led = walk_objmap(cus, cusprops_body_len, stop=end_off)
    assert led.end_offset == end_off
    assert serialize_objmap(led) == cus[:end_off]


@pytest.mark.layer2
@pytest.mark.skipif(not CORPUS, reason="no corpus CusProps")
@pytest.mark.parametrize(("tag", "path"), CORPUS, ids=_IDS)
def test_objmap_ledger_threshold_matches_object_map_walk(tag: str, path: Path) -> None:
    """The ledger's next_index after the user-record region equals the
    independent _object_map_walk threshold — two separate computations of the
    object-map index agreeing is a strong correctness check, and it is the
    renumber threshold Step C (insert) needs."""
    from swformat.carchive.cusprops import (
        _object_map_walk,
        cusprops_body_len,
        parse_container_header,
        walk_user_records,
    )
    from swformat.carchive.objmap import walk_objmap

    cus = swformat.read_document(path).streams().get("Contents/CusProps")
    if cus is None:
        pytest.skip("no CusProps")
    try:
        n_props, _f, _ = parse_container_header(cus)
    except CustomPropsError:
        pytest.skip("unparseable")
    if n_props == 0:
        pytest.skip("empty store")
    _recs, end_off = walk_user_records(cus)
    led = walk_objmap(cus, cusprops_body_len, stop=end_off)
    _cmap, threshold, _e = _object_map_walk(cus)
    assert led.next_index == threshold
